name: Deploy Azure Infrastructure Visualizer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  # Checkout the code
    
    - name: Set up Python 3.9
    - uses: actions/checkout@v3
      with:
        python-version: 3.9  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt     
